# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: tombi-toml.tombi
PackageVersion: 1.7.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: tombi.exe
  PortableCommandAlias: tombi
InstallationMetadata:
  DefaultInstallLocation: '%LOCALAPPDATA%\Microsoft\WinGet\Packages\tombi-toml.tombi__DefaultSource'
  Files:
  - RelativeFilePath: tombi.exe
    FileType: launch
    InvocationParameter: --version
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/tombi-toml/tombi/releases/download/v1.7.1/tombi-cli-1.7.1-x86_64-pc-windows-msvc.zip
  InstallerSha256: 4ABEE0008E4C18F2D0B8FCEA72B5F1D73B04B398D3B1CF63D73040D1420E9CAA
- Architecture: arm64
  InstallerUrl: https://github.com/tombi-toml/tombi/releases/download/v1.7.1/tombi-cli-1.7.1-aarch64-pc-windows-msvc.zip
  InstallerSha256: D6AE2220EBF4F71E0CAA57B82B93048369068A67E62CB75FF4E73415F32F3851
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-02
