# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: tombi-toml.tombi
PackageVersion: 1.7.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: tombi.exe
  PortableCommandAlias: tombi
InstallationMetadata:
  DefaultInstallLocation: '%LOCALAPPDATA%\Microsoft\WinGet\Packages\tombi-toml.tombi__DefaultSource'
  Files:
  - RelativeFilePath: tombi.exe
    FileType: launch
    InvocationParameter: --version
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/tombi-toml/tombi/releases/download/v1.7.0/tombi-cli-1.7.0-x86_64-pc-windows-msvc.zip
  InstallerSha256: 13822150C15D37A76C989BB7B8F1E6433625B4E72A21DCAB10B03D5D46386950
- Architecture: arm64
  InstallerUrl: https://github.com/tombi-toml/tombi/releases/download/v1.7.0/tombi-cli-1.7.0-aarch64-pc-windows-msvc.zip
  InstallerSha256: D1883C1D1167F823CC7C91BDE2E41DF3DA24016F5E9C4BA37CA6E96798EBA01F
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-01
